name: API CI - RealEstate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test API en Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16.x, 18.x]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cachear dependencias
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas con Jest
        run: npm test

      - name: Reportar éxito
        if: success()
        run: echo "✅ API funcional en Node ${ { matrix.node } }"

      - name: Reportar fallo
        if: failure()
        run: echo "❌ Error detectado en los tests para Node ${ { matrix.node } }"
